#!/bin/sh

######################################
# sdorfehs rc setup file
# izder456 2022 <izder456@disroot.org>
######################################

exec feh --bg-fill /usr/share/backgrounds/gruvbox.png

escape C-t
set bgcolor 32302f
set fgcolor d5c4a1
set barsticky 1
set barbordercolor 32302f
set border 0
set gap 8
set bargravity ne
set font Unifont
alias scrot exec scrot
alias volume-up exec pulseaudio-ctl up
alias volume-down exec pulseaudio-ctl down
alias volume-mute exec pulseaudio-ctl mute
alias volume-mute-mic exec pulseaudio-ctl mute-input
bind space exec rofi -show drun
definekey top Print scrot
definekey top XF86AudioRaiseVolume volume-up
definekey top XF86AudioLowerVolume volume-down
definekey top XF86AudioMute volume-mute
definekey top XF86AudioMicMute volume-mute-mic
bind L exec betterlockscreen --lock blur
bind f exec firefox-bin
bind q quit
exec ~/.local/bin/bar.sh &
exec xterm &
