#!/bin/sh
# 
# $OpenBSD: Xstartup.in,v 1.4 2018/07/15 09:53:23 matthieu Exp $
#
prefix="/usr/X11R6"
exec_prefix="${prefix}"

if [ -f /etc/nologin ]; then
        ${exec_prefix}/bin/xmessage -file /etc/nologin -timeout 30 -center
        exit 1
fi
exec ${exec_prefix}/bin/sessreg -a -l $DISPLAY -u none $USER
