#!/bin/ksh
prefix="/usr/X11R6"
exec_prefix="${prefix}"

# Kill XCLOCK, XMESSAGE, & XCONSOLE upon Session Load
pkill xclock
pkill xconsole
pkill xmessage

chown $USER /dev/console
if [ -c /dev/dri/card0 ]; then
    chown $USER /dev/dri/card0
fi
if [ -c /dev/dri/renderD128 ]; then
    chown $USER /dev/dri/renderD128
fi
${exec_prefix}/bin/sessreg -a -l $DISPLAY -u none $USER
