#!/bin/ksh

xrandr --output default --dpi 96
xset b on
xset fp+ /usr/local/share/fonts/spleen
prefix="/usr/X11R6"
exec_prefix="${prefix}"

XWIDTH=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d 'x' -f 1)
XHEIGHT=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d 'x' -f 2)

/usr/local/bin/feh --bg-fill "$(/usr/local/bin/shuf -n1 -e /usr/local/share/backgrounds/*)" &

XCLOCK_WIDTH=128
XCLOCK_HEIGHT=128
XCLOCK_YOFFSET=64
XCLOCK_XPOS=$((($XWIDTH - $XCLOCK_WIDTH) / 2))

XMESG_WIDTH=256
XMESG_HEIGHT=64
XMESG_YOFFSET=256
XMESG_XPOS=$((($XWIDTH - $XMESG_WIDTH) / 2))

XCONSOLE_WIDTH=512
XCONSOLE_HEIGHT=128
XCONSOLE_YOFFSET=128
XCONSOLE_XPOS=$((($XWIDTH - $XCONSOLE_WIDTH) / 2))

(
while true; do
    xmessage -center \
        -buttons "(-SLEEP[])":20,"(-RESTART[])":21,"(-SHUTDOWN[])":22 "" \
        -geometry ${XMESG_WIDTH}x${XMESG_HEIGHT}+${XMESG_XPOS}+${XMESG_YOFFSET}
    ACTION=$?
    echo "Xmessage said: $ACTION"
    if   [ $ACTION -eq 20 ]; then /usr/sbin/zzz;
    elif [ $ACTION -eq 21 ]; then
      xsetroot -cursor_name watch
      /sbin/shutdown -r now
    elif [ $ACTION -eq 22 ]; then
      xsetroot -cursor_name watch
      /sbin/shutdown -p now
    else echo "Something bad happened to Xmessage.";
    fi
    if [ -z "$(pgrep -U root xconsole)" ]; then break; fi
done
) &

xconsole -daemon -notify -verbose -exitOnFail -geometry \
${XCONSOLE_WIDTH}x${XCONSOLE_HEIGHT}+${XCONSOLE_XPOS}-${XCONSOLE_YOFFSET} &

xclock -analog -update 1 -padding 12 -sharp -geometry \
${XCLOCK_WIDTH}x${XCLOCK_HEIGHT}+${XCLOCK_XPOS}+${XCLOCK_YOFFSET} &

(sleep 5 && xwd -out /tmp/xenodm.xwd -root) &
